services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /pgdata
    command:
      - 'postgres'
      - '-c'
      - 'wal_level=logical'
    ports:
      - '5432:5432'
